### PR TITLE
Better comments item meta wrapping

### PR DESCRIPTION
**Pull request by oetherington**
This is a first attempt at improving the display of comment information on small screens. This probably isn't a totally finished solution, but it should at least get us into the territory of "this design could be better" instead of "this is a bug".

The diff is ugly because I refactored a ton of code out of `CommentsItem` into a separate `CommentsItemMeta` component as it was getting pretty unweildly. The only real changes here are in `styles` in `CommentsItemMeta` - splitting it up just made it easier to work out what I needed to change.

I've not forum gated these changes because this is also pretty clearly broken on LessWrong prod as well:
Screenshot 2023-03-31 at 23 00 46

The new approach is to always pin the three dot menu (and, on the EA forum only, the link button) to the top right and allow everything on the left to wrap. On the EA forum this looks like this:
Screenshot 2023-03-31 at 23 24 22
Screenshot 2023-03-31 at 23 24 27

And on LessWrong:
Screenshot 2023-03-31 at 23 21 12
Screenshot 2023-03-31 at 23 21 39

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204312577109342) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by s-cheng** [comment]
Reassigning to @jpaddison3 since I'll be out for the next couple working days

**Comment by oetherington** [comment]
Just added another commit to fix the bug where "Answer by" comment authors are shown in serif:
Screenshot 2023-04-03 at 13 31 58

**Comment by jpaddison3** [comment]
I could not reproduce the LW bug at reasonable screen resolutions, but also don't see a noticeable change to the LW behavior, and the code changes are sensible.

FYI @darkruby501, NNTR if you trust me.

**Review by jpaddison3 — APPROVED** [review]
LGTM

**Comment by darkruby501** [comment]
Looks good! What is NNTR...

**Comment by jpaddison3** [comment]
No Need To Respond (perhaps ironically)

**Comment by jpaddison3** [comment]
I don't think we need an @agnesstenlund review here.

**Pull request merged**
