### PR TITLE
Fix community tag permissions

### PR DESCRIPTION
**Pull request by oetherington**
Permission to vote on a particular tag is controlled by the database field `canVoteOnRels` on the `Tags` collection. This PR makes this setting also apply to actually _adding_ the tag instead of just to voting on it.

I've also updated the setting in the DB to also give permission to `sunshineRegiment` instead of just `admins`.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203844801808820) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by s-cheng** [comment]
@oetherington Is this really the behavior we want? So users can't tag their own posts as "community"?

**Comment by jpaddison3** [comment]
Given that they cannot remove they tag if they apply it, and that it means that other non-admins can apply it to posts they don't like, I voted in favor of this change.

**Comment by jpaddison3** [comment]
Maybe an exception should be made for your own post? Ideally you'd be able to remove your own vote, which maybe actually would work? IDK, sounds like a bit of a faff.

**Comment by s-cheng** [comment]
@oetherington I just tested this locally and I'm still able to add the Community tag to posts as a normal user (and can't remove them).

**Comment by oetherington** [comment]
@s-cheng Are you 100% the user you tested on wasn't in sunshineRegiment? I just tested it again and couldn't reproduce the problem.

**Review by s-cheng — APPROVED** [review]
Not sure what happened before (I've never assigned one of my users to sunshine...) but now I don't see any issues. :) I do think we should remove the "Community" tag from the list in the post editor, now that users can't actually assign it to their posts.

**Comment by jpaddison3** [comment]
> I do think we should remove the "Community" tag from the list in the post editor, now that users can't actually assign it to their posts.

That seems important to bundle with this PR.

**Comment by oetherington** [comment]
Just added a commit to hide community from the list for non-admins/moderators. I don't love the solution because it means hard-coding a separate list of tags, but I don't see any straightforward to make the database settings available from the frontend.

**Comment by s-cheng** [comment]
@oetherington Thanks! I was actually thinking of the "Post Topics" list, where "Community" can appear in either the subforums list (currently just on staging since it's not a subforum on prod) or the core topics list:

Screen Shot 2023-02-06 at 4 24 34 PM
Screen Shot 2023-02-06 at 4 24 45 PM

**Comment by oetherington** [comment]
Whoops - forgot that existed. See #6650.

**Pull request merged**
