### PR TITLE
Post page top tag

### PR DESCRIPTION
**Pull request by jpaddison3**
The second step towards the [sprint prototype](https://www.figma.com/file/lYIUu1lWDFpjJKp4nLqny7/Forum-topics-Design-Sprint-Prototype), we're adding a highlighted core tag above the title on the post page. This is to improve the experience of new users not knowing where to go after they read a post, and trying to give them a place to find content relevant to their interests.

image

image

### CODE REVIEW

**Comment by Oldmantax** [comment]
This seems great - does this include a decision about what the top tags are? I expect this to be tricky intellectually and politically.

**Comment by Oldmantax** [comment]
Looks like the list is:
 - community
 - biosecurity
 - x-risk
 - cause prio
 - moral philosophy
 - wild animal welfare
 -  farmed animal welfare
 - groups
 - career choice
 - AI alignment
 
Reactions to this:
- I think moral philosophy is too niche for this degree of prominence, we should make it part of cause prio
- Similarly, I propose merging wild and farmed animal welfare
- Not sure what you mean by groups, but I propose moving it under community
- I might add something on governance/policy?
- I'm a bit confused how the "X risk" tag will relate to the AI alignment/bio tags: presumably it would also apply to all of the articles that those tags would be on. Maybe it should be "other X/cat risks"?
- Global poverty? Or neartermist human welfare or something
- I'm tempted to replace "career choice" with something broader like "take action" (which currently links to job postings etc.) Less sure about this.

Also, it seems like there's some move to make "community" different from the other tags? I think it should be ~the same.

**Review by jcmustin — APPROVED** [review]
Broadly agree with Max's tag suggestions—moral philosophy seems worth keeping to me, and I think I would vote for 'career choice' over 'take action', but I don't feel strongly about either, and otherwise his suggestions seem good to me 🙂. 

Everything else seems good. Nice work! 🙌

**Comment by jpaddison3** [comment]
I'm just using core tags here. I would like to change them, but would not like to change them before shipping this.

**Comment by Discordius** [comment]
Oh, I actually like the design for this. But how does this interface with the sequences navigation?

**Comment by jpaddison3** [comment]
@Discordius Doesn't appear if those are present.

**Pull request merged**
