### PR TITLE
Add join button to subforum

### PR DESCRIPTION
**Pull request by Will-Howard**
Screenshot 2022-09-16 at 18 33 45
Screenshot 2022-09-16 at 18 34 05

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202997053679280) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by s-cheng** [comment]
@Will-Howard @jpaddison3 Wait, we're using `frontpageFilterSettings` to track subforum membership? I thought we were going to use `profileTagIds`?

**Comment by jpaddison3** [comment]
I am an idiot

**Comment by jpaddison3** [comment]
I had a memory have having a better idea than frontpage filter settings, but forgot about profileTagIds

**Comment by jpaddison3** [comment]
@Will-Howard I think we need to refactor. Would you be able to do that?

**Review by jpaddison3 — APPROVED** [review]
:shipit:

**Comment by jpaddison3** [comment]
Merging this because I want it.

**Pull request merged**
