### PR TITLE
hideFromAuthorPage sequences

### PR DESCRIPTION
**Pull request by Raemon**
This makes it so admins can make sequences that are hidden from their author page (mostly motivated so that my author page isn't dominated by Best Of LessWrong sequences)

### CODE REVIEW

**Comment by darkruby501** [comment]
Why is this only for admins?

**Comment by Raemon** [comment]
The use case is primarily admins making sequences that are more "for the site" than associated with that particular admin. It maybe makes sense to open up to other users, but mostly seemed like unnecessary complexity to expose them to.

**Comment by darkruby501** [comment]
I recall users having wanted this, so think it might make sense to have the option for them. I think people don't like their user page being cluttered up.

**Review by darkruby501 — APPROVED** [review]

**Review by Xodarap — COMMENTED** [review]
:shipit:

**Pull request merged**
