### PR TITLE
Support Neuronpedia embeddings

### PR DESCRIPTION
**Pull request by hijohnnylin**
**Objective**
We would like to support Neuronpedia embeds in LessWrong posts. Neuronpedia is used by interpretability researchers as a database/reference for looking at "neurons" inside AI models. Each of these neurons has rich details, examples, and metadata that Neuronpedia stores. We would like to allow readers to directly see these details, as well as interact with the neurons, instead of having to open a new tab/window to do it.

**Code**
I implemented the feature to the best of my ability, by looking at embed examples from Manifold https://github.com/ForumMagnum/ForumMagnum/pull/4907 and others.

**Testing**
I tested it on a new local environment. The embed shows up correctly in the draft composition page, but I am unable to save the draft locally (possibly because I am missing some local environment setting). I am not 100% sure that it will show up correctly once the post is actually posted. See screenshot from my local environment:
image

**Question**
It isn't super critical that we have this feature now, but for some reason, I'm not able to get the "paste a non-embed link and automatically convert it into an embed link" feature to work. This is in `PostLinkPreview.tsx`, and it seems to work fine for Manifold. I'm not sure how to debug this, or if I'm supposed to use a command other than `yarn run rebuild-ckeditor` to get this working. I would appreciate any assistance on this, but it's also totally ok if we don't have it right now.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207794797616537) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by Will-Howard** [comment]
@jimrandomh @b0b3rt Would one of you like to take this one, given it's intended for LessWrong?

**Comment by b0b3rt** [comment]
@Will-Howard yeah we'll review it.

**Comment by b0b3rt** [comment]
@hijohnnylin I've now had a chance to test this.

The issue you were running into with links without `?embed=true` not being replaced by an embed when pasted into the editor was because the regex was slightly wrong - I think it should be `/^neuronpedia\.org\/([a-zA-Z0-9-/]*)(?:\?embed=true)?/` (along with changing the iframe `src` to `https://neuronpedia.org/${longslug}?embed=true`, since it now puts the query param in a non-capturing group), though I'm not a regex expert and possibly this is missing some edge cases you might care about, like if there are additional query parameters.

`PostLinkPreview` is unrelated to that and is used to implement tooltip previews when links are hovered over, so is useful for the case when someone puts an [inline link](https://neuronpedia.org/gpt2-small/0-res-jb/14057) (like that one) to a neuronpedia element in their post/comment and another user hovers over that link.  That part seems to work correctly for both the embed/non-embed link cases, and did require saving the post draft to test.

After you update the regex I'll approve & merge this PR.  Thanks!

**Comment by hijohnnylin** [comment]
thanks @b0b3rt ! (I'm no regex expert either, please bear with me). I am still confused about why the regex isn't working, so I'll try to describe the possible issues below:

I noticed your regexes don't have `https://` or `www` - should we leave those out? (I'm not sure what preprocessing is done at that step already). I see some of the others do include it - eg Metaforecast right below it does include https.

For the regex change, I'm still confused why it's not working.

Desired behavior:
1) User pastes non-embed link (like `https://neuronpedia.org/gpt2-small/0-res-jb/0`)
2) Editor converts it to an embed link: `https://neuronpedia.org/gpt2-small/0-res-jb/0?embed=true&embedexplanation=true&embedplots=true&embedtest=true&height=300`
3) Embed link is converted to iframe

The current code:
1. `const results = href.match(/^https?:\/\/(www\.)?neuronpedia\.org\/([a-zA-Z0-9-/]+).*/) || [];` receives `https://neuronpedia.org/gpt2-small/0-res-jb/0` as `href`. According to regexr.com, this is a match: 
image

2. At this point, `results` should equal `true` with a non-zero length.

3. Since !isEmbed and results has values, it should NOT return the simple non-iframe.

4. We get the slug from the results, which is `gpt2-small/0-res-jb/0`

5. We create the `const url = ...` embed url, then put it into the iframe.

I converted it to a typescript playground here:
https://www.typescriptlang.org/play/?#code/ATBQDcEMCdgC2gUwGbALzAERwC44A4DOAXAPSkB2iArtAPYX6IAmAlpAHR3QDmpP+HACYAtIQC2kADZTSABhFJCIgFYAjeZlABjBoRzAl1KTkLp4SZB0k5tcABSkAergKEA-MQA6pH-YDugV4cAJTuVLQMTGyQwdw8fgDakCIAXgCCIgBaCgCcIqQAugDUIRwAVKQhoKCsqPYAhEYmZgA+rYaIhMamHFKIFDw4cOhoGHIhwADeoCAguhSEdP19dDz2mAASlsDMdF3AFHQGNnbAdLSdPIgAHsAih8fAkIc09Iws7MBSrBQA1hxMNUAL6gRBSQiIaazOYLJYrKRrDbbFC7fZmU4jC6wJDXO4PYasMxE56vSIfGLfX4A4AAdShhDgFykzGAOFoFGArAMvxwdGenMQ4jULCp-0B1Tm30QBkIUmoPHMzVMiWVhD6AyGIweAEZCjD5nplohVusAAZyhXEYAAEimlp4wLNkthegMtCk5jNriIZEobyin048VIdrVqq6PXV-UGw3uwD1wPcQpFzDQOGg1EQADIUyxbvgpJAKJAcKwGOnMzm88xC8dCJWs2aANwG4Bw42m+wekGgIA

```
var href = "https://neuronpedia.org/gpt2-small/0-res-jb/0"
const results = href.match(/^https?:\/\/(www\.)?neuronpedia\.org\/([a-zA-Z0-9-/]+).*/)

if (!results || results.length === 0) {
    console.log("Href does not match our regex - not a neuronpedia link.")
}
else {
    console.log("Href does match our regex - this is a neuronpedia link. We should turn it into an embed link.")
    let slug = results[results.length - 1]
    console.log(`slug: ${slug}`)
    const url = `https://neuronpedia.org/${results[results.length - 1]}?embed=true&embedexplanation=true&embedplots=true`;
    console.log(url)
}
```

I could be misunderstanding your suggestion, but your suggestion seems to say that we should add `(?:\?embed=true)?` to the regex - but we don't want to match the `embed=true` in this case, because the user has not pasted in an embed link. They pasted in a regular link without embed, and we want to convert it to one that has embed=true&[and other parameters].

**Comment by hijohnnylin** [comment]
please disregard the comment above -  i misunderstood you and will push a new commit to this PR

**Comment by hijohnnylin** [comment]
The change has been pushed, thank you so much! It seems to work great locally.

**Comment by b0b3rt** [comment]
@hijohnnylin does the updated regex (`/^neuronpedia\.org\/([a-zA-Z0-9-/]*)(?:\?embed=true&embedexplanation=([a-zA-Z0-9-/]*)&embedplots=([a-zA-Z0-9-/]*)&embedtest=([a-zA-Z0-9-/]*)&height=([a-zA-Z0-9-/]*))?/`) correctly work with links like `https://neuronpedia.org/${longslug}?embed=true` which don't have all 5 query params (embed, embedexplanation, embedplots, embedtest, and height)?  I haven't tested it but it looks like it expects either all 5 or no query params at all.  It does look like the embed links generated on neuronpedia have all 5, but unless links with more than 0 but less than 5 params are actually malformed and should be ignored, it seems likely to confuse some users at some point.

**Comment by hijohnnylin** [comment]
Yes, I just tried it and it does work properly on all three cases:

1) Non-embed link: `https://neuronpedia.org/gpt2-small/0-res-jb/0`
2) Embed link with no options: `https://neuronpedia.org/gpt2-small/0-res-jb/0?embed=true`
3) Embed link with options: `https://neuronpedia.org/gpt2-small/0-res-jb/0?embed=true&embedexplanation=true&embedplots=true&embedtest=true&height=300`

I believe I made the behavior so that it will fallback to defaults on the other values when they do not exist.

**Review by b0b3rt — APPROVED** [review]

**Pull request merged**
