### PR TITLE
[EA Forum only] followup UI tweaks after removing post item bookmark icon

### PR DESCRIPTION
**Pull request by s-cheng**
Addressing @agnesstenlund's comments in https://github.com/ForumMagnum/ForumMagnum/pull/7033, as well as adjusting the post item for logged out users (who can't see the three dots menu)

Logged in view:
Screen Shot 2023-04-27 at 2 51 35 PM

-----
Logged out view:
Screen Shot 2023-04-27 at 2 42 53 PM

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204490813164384) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by agnesstenlund** [comment]
This looks perfect, thank you 🏆 

Unlike your screenshots I'm still seeing it horizontally though:
Screenshot 2023-04-27 at 21 27 50

I don't mind either way though, can see arguments in favor of both horizontal and vertical

**Comment by agnesstenlund** [comment]
in the future it'd be nice if logged out people could still see the ... and when they click on an option in there (like bookmark) we prompt them to log in. But, for another PR :)

**Comment by s-cheng** [comment]
@agnesstenlund oops I changed it to take a screenshot and forgot to change it back before committing lol - thanks for flagging!

**Review by Will-Howard — APPROVED** [review]
🦭

**Pull request merged**
