### PR TITLE
Visited links have a filled-in circle

### PR DESCRIPTION
**Pull request by jimrandomh**
Visited links now have a filled-in circle instead of a hollow circle, to indicate that they're visited. This currently supplements the link color change, rather than replacing it, but part of the goal here is to make the link color change unnecessary so that we can consider dropping it.

This also makes the visited-status of links depend on both the browser history and on whether the post/tag/etc is marked as read in the database (if you're logged in), rather than only being based on the browser history, so the visited-status now carries over between devices/browsers/etc if you're logged in.

Screenshot 2024-10-18 at 12 17 08

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208581002801296) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by s-cheng** [comment]
😮

**Comment by jimrandomh** [comment]
Still waiting for review. Does EAF want this forum-gated?

**Review by b0b3rt — APPROVED** [review]

**Comment by b0b3rt** [comment]
(I don't have a strong opinion here, but probably does want EA forum buy-in if not feature-gated.)

**Comment by jimrandomh** [comment]
Got conflicting opinions on forum-gating (and saw Agnes' reply before I saw Sarah's), so I wound up forum-gating this. It's `visitedLinksHaveFiledInCircle` in betas.ts so easy to change.

White testing the forum-gating, I noticed that when links are in local browser history but not marked as read server-side, eg because you're logged out, it wasn't working because of browser history-sniffing protection. That's pretty important, and now fixed.

**Pull request merged**
