### PR TITLE
[EA] Edit user profile page redesign

### PR DESCRIPTION
**Pull request by oetherington**
Redesign of the edit profile page. [Figma](https://www.figma.com/design/qAHRGADVOGojqKpqbGMFFu/2024-Q2?node-id=943-13769&m=dev).

Edit-Profile-—-EA-Forum-localhost

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207506060063672) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by oetherington** [comment]
@agnesstenlund I'm going to open this one up for review now.

There's still one issue: we still have the ugly "clear" button underneath the "organizer of" field. There's currently not an easy way to remove it, but I added a way to remove it in the "Vibes check" PR, so we can merge that first and then easily remove the "clear" button here.

**Comment by agnesstenlund** [comment]
Wow this looks so good!! Thank you

**Comment by agnesstenlund** [comment]
I'll go in and make some small CSS-tweaks (think it's only margin + padding things) but otherwise this looks great

**Comment by agnesstenlund** [comment]
Made some small tweaks, here are some that took longer for me/ wasn't sure how it'd affect other places:

- [ ] A bit too much vertical space in-between each input here
Screenshot 2024-06-22 at 17 48 18

- [ ] Could we use the dropdowns from onboarding/ people directory instead, the ones that appear below? Could that be a component we reuse?
Screenshot 2024-06-22 at 17 40 22

- [ ] "Search for topics" should be closer to the topic pills
Screenshot 2024-06-22 at 17 49 17

- [ ] Would also feel more standard if the "Search for topics" wrapped and was the first thing on a new line instead of staying in place as you keep adding topics (I also think it looks a little bit weird to have the box sort of expand when you search vs. it appearing in a dropdown on top of the input, but that's not a huge deal if it's complicated to do)
Screenshot 2024-06-22 at 17 55 56
Screenshot 2024-06-22 at 17 55 37

- [ ] All inputs should have the same font size + weight, right now I think most should be 14px font-weight 500, but e.g. the social media inputs are 1rem instead

**Review by jpaddison3 — APPROVED** [review]

**Pull request merged**
