### PR TITLE
Greatly reduce size/redundancy in the stylesheet

### PR DESCRIPTION
**Pull request by jimrandomh**
This reduces the size of `allStyles` from 1.6MB uncompressed/125kb compressed to 406kb uncompressed/57kb compressed.

The bulk of our stylesheet was taken up with duplicate copies of deeply nested post/comment styles, generated as a result of importing and object-spreading from `stylePiping.ts` with variations on this:
```
  body: {
    ...commentBodyStyles(theme),
  },
```

This PR introduces a component `ContentStyles`, which handles all of the things that were previously done with this sort of import-and-spread. It then also applies multiple classes, which replaces usages of `deepmerge` within `stylePiping.ts`. If I did all of this correctly, there should be no visual changes to anything. I have inspected some but not all of the components as I was transforming them, and I checked the front page and post pages. The biggest risk is accidental changes in the size of margins in some less-used places, due to trickiness with CSS precedence.

### CODE REVIEW

**Comment by jimrandomh** [comment]
A couple unrelated commits by JP (from the `CloudinaryImage2` PR) seem to have gotten caught up in a rebase; they are not actually changed relative to master.

The Cypress test failure is due to a class-name changing and the test looking for it, I'll fix that.

**Comment by s-cheng** [comment]
@jimrandomh FYI I checked this branch out and loaded the EA Forum home, and I see this error in the console:

```
Warning: Prop `style` did not match. Server: "null" Client: "color:"
    at svg
    at SvgIcon (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:53353:28)
    at WithStyles2 (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:21105:44)
    at KeyboardArrowUpIcon
    at ShouldUpdate2 (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:53094:31)
    at Transition5 (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:57097:34)
    at span
    at button
    at ButtonBase2 (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:59741:40)
    at WithStyles2 (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:21105:44)
    at IconButton (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:65014:28)
    at WithStyles2 (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:21105:44)
    at VoteArrowIcon (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:177364:27)
    at http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:248870:50
    at VoteButton (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:177576:13)
    at WithTheme2 (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:21336:44)
    at OverallVoteButton (http://localhost:3000/js/bundle.js?hash=47b9341602eb71ff381e1a44362f6ee4d8527bfc3bfb8472bdace9e7db3514f1:177655:13)
...
```

I also see 3 typescript errors, such as this:
```
packages/lesswrong/lib/crud/withCreate.tsx:55:7 - error TS2322: Type '(mutate: any, { data }: { data: any; }) => Element' is not assignable to type '(mutateFunction: MutationFunction<any, Record<string, any>>, result: MutationResult<any>) => Element | null'.
  Types of parameters '__1' and 'result' are incompatible.
    Type 'MutationResult<any>' is not assignable to type '{ data: any; }'.
      Property 'data' is optional in type 'MutationResult<any>' but required in type '{ data: any; }'.
```

**Comment by jimrandomh** [comment]
The Typescript error in `withCreate` is a symptom of having upgraded the Typescript compiler without the corresponding type-annotation fixes being present. The `style` mismatch in `OverallVoteButton` looks like maybe a React 18 thing; in any case it's not replicating for me after merging from master.

**Review by s-cheng — APPROVED** [review]
Looks good! I clicked around on the EA Forum and only noticed one styling issue.

**Comment by jimrandomh** [comment]
Merged as part of https://github.com/ForumMagnum/ForumMagnum/pull/3909

**Pull request closed without merging**
