### PR TITLE
Remove Type3 webhooks

### PR DESCRIPTION
**Pull request by s-cheng**
Based on [this slack message](https://cea-core.slack.com/archives/C048F7FRLBX/p1697815497822989) from Type3, they don't need this anymore

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205847903062118) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by s-cheng** [comment]
@b0b3rt I don't think LW is using these, but flagging just in case

**Comment by b0b3rt** [comment]
@s-cheng I'm not actually sure if we need them or not - I'll ask Type3 whether we need to maintain them for LW or if they're being deprecated for all users.

**Comment by b0b3rt** [comment]
@s-cheng Type3 said we're fine, so 👍

**Review by b0b3rt — APPROVED** [review]

**Review by Will-Howard — APPROVED** [review]
👍

**Pull request merged**
