### PR TITLE
[WIP] Streaming responses

### PR DESCRIPTION
**Pull request by jimrandomh**
Implements streaming responses. What this means is, when you request a page, rather than render the page and then send it, we will send the page's preamble, then render the page, then send the rest. The preamble includes the URLs of static resources like CSS and Javascript, so this means that the browser can take advantage of time that would otherwise be spent waiting for the server to do its SSR, to get those downloaded and ready.

Caveats:

* Status codes (301 redirect, 404 not found) don't work yet. Fixing this requires separating redirect-handling and missing-document-detection from rendering, probably by moving it into the routes table.
* Resources loaded with `Helmet` still can't start until after render, which currently includes webfonts, which involve two roundtrips (even on a cache hit) and block the first paint. (But they should be easy to move earlier.)
* Bug fixes were needed to Meteor's `server-render` and `boilerplate-generator` packages to not accidentally convert streams into the string "[Object object]" on their way through. These fixes should be upstreamable.
* In `boilerplate-generator`, I moved scripts file imports from the bottom of the file to the top of the file and gave them a `defer` attribute. This preserves execution order, except if someone used WebAppInternals.addStaticJs (we don't), in which case execution order can't be preserved because inline scripts (as opposed to reference-to-file scripts) can't have the `defer` flag. This might make that part harder to get upstreamed.
* I had to disable the `compression` middleware, because it doesn't start passing things through a stream until it's filled a window which the header isn't big enough to fill, or you call its `flush` method. This needs to be fixed in Meteor's `webapp` package.

As todos:

* [ ] Get status codes working
* [ ] Move webfonts out of Helmet, into the streamable part of the header
* [ ] Upstream the fixes to `server-render` and `boilerplate-generator`
* [x] Make this work with the `compression` middleware and re-enable it

┆Issue is synchronized with this [Trello card](https://trello.com/c/qtZxdu2T) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by Discordius** [comment]
Hmm, doesn't compression matter a whole lot? So we might have to make sure to fix that somehow before we can merge this.

**Comment by jimrandomh** [comment]
Yep, we definitely can't ship without fixing the compression middleware.

**Comment by jimrandomh** [comment]
Another possibility would be to move to a multi-process architecture, with a proxy in front of the main server process, and have the proxy do the compression. If we could get the proxy to also handle static resources and caching, this would have a significant side benefit; currently, because our server is single-threaded and handles everything, trivial static resources can be delayed by getting queued up behind rendering.

**Comment by jimrandomh** [comment]
This PR is thoroughly moot now that we're not on Meteor, and have streaming-ish reponses in the Express-only context.

**Pull request closed without merging**
