### PR TITLE
Right recommendation redesign

### PR DESCRIPTION
**Pull request by oetherington**
Redesign of recommendations on the right of the post - [Figma](https://www.figma.com/file/d09iVzNSpZp9GyWGcfkWmX/Q2-2023?node-id=1767%3A85777&mode=dev).

These changes probably break the display of the "More from the forum" option a little, but that's currently disabled so we can worry about fixing it if/when we reenable it.

Screenshot 2023-08-10 at 19 19 37
Screenshot 2023-08-10 at 19 19 44
Screenshot 2023-08-10 at 19 19 20
Screenshot 2023-08-10 at 19 20 07

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205242610903596) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by oetherington** [comment]
CC @agnesstenlund

**Comment by jpaddison3** [comment]
I feel like the spacing feels off to me, maybe because of the thinner box, or maybe because of the "give feedback" button.

**Comment by agnesstenlund** [comment]
wow somehow this fell through the cracks–sorry about that! Looking at the localhost now and am not seeing any changes 😮  not sure what's up here
Screenshot 2023-08-29 at 17 44 47

**Comment by agnesstenlund** [comment]
from the screenshots I can say I agree with JP that something about the padding feels odd, I think mainly the titles need to be able to wrap further, looks like they get cut off a little too early on the right. Karma could probably also be placed slightly further to the left to give some more space.

And with this new design it'd probably look better to move the "Give feedback" to the left

**Comment by oetherington** [comment]
As discussed yesterday, I'm merging as-is and also disabling the AB test and right-hand side recommendations. We can fix the padding issues if we ever experiment with this again.

**Pull request merged**
