### PR TITLE
Quick takes styling tweaks

### PR DESCRIPTION
**Pull request by oetherington**
This PR changes the typography in collapsed quick takes to match expanded quick takes, and adds a bottom margin underneath expanded quick takes.

Screenshot 2023-06-28 at 15 54 16

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204925953274488) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by oetherington** [comment]
@agnesstenlund I included the typography changes and the bottom margin in this PR. I made [a separate Asana ticket](https://app.asana.com/0/628521446211730/1204910046501723/f) for the padding between comments, because it turns out it's pretty difficult to do unfortunately.

**Comment by agnesstenlund** [comment]
looks perfect! ✨ only thing I'd change is the padding between comments which looks a little too big now (would cut in ~half)
Screenshot 2023-06-28 at 18 20 46

**Comment by agnesstenlund** [comment]
probably same for in-between shortforms too actually, would cut the space in half

Screenshot 2023-06-28 at 18 22 58

**Comment by agnesstenlund** [comment]
oh sorry didn't see your first comment there–thought the comment padding had changed already! 😅

**Comment by agnesstenlund** [comment]
unrelated: would maybe not actually make the comment icon hoverable and clickable, since the interaction there feels unexpected and it's easier to just expand the shortform and scroll down (vs clicking, being taken to the authors shortform page with the shortform expanded, then still have to scroll down)

**Review by agnesstenlund — APPROVED** [review]

**Review by s-cheng — APPROVED** [review]
👍 

I agree with @agnesstenlund that the spacing under each item seems a bit too big now, I'll let you two figure out the exact amount

**Comment by oetherington** [comment]
Thanks! I'm going to go ahead and merge this now.

Re "would maybe not actually make the comment icon hoverable and clickable": I'll fix this separately

**Comment by oetherington** [comment]
I reduced the margin to 8px (we can tweak further in a separate PR if needed)

Screenshot 2023-07-03 at 13 14 23

**Comment by agnesstenlund** [comment]
looks perfect!

**Pull request merged**
