### PR TITLE
[EA Forum only] sticky digest ad on the post page

### PR DESCRIPTION
**Pull request by s-cheng**
We're iterating on the [previous post page digest ad](https://github.com/ForumMagnum/ForumMagnum/pull/8621), which got us very few subscriptions. See designs and discussion in [slack](https://cea-core.slack.com/archives/C03G0AQ925P/p1706712536726979?thread_ts=1706542113.434749&cid=C03G0AQ925P).

This one appears at the bottom of your screen once you have scrolled down somewhat on a post page. It doesn't appear on very small screens. We're starting it out behind an A/B test, showing it to 20% of users/clients (so in practice close to half of that since about half will be mobile).

A couple screenshots:
Screen Shot 2024-02-08 at 12 34 38 AM
Screen Shot 2024-02-08 at 12 35 48 AM

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206551734037123) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by agnesstenlund** [comment]
Looks great!! I can't see it locally despite logging out + seeing the other digest ad. Is that expected?

Dark mode looks good in your screenshot, I'd only change the text input to white (and if the contrast is then too low between the grey bg and the white input we could make the bg a tiny bit darker)

**Comment by agnesstenlund** [comment]
Oh we probably also want to disable the "Sign up" button (and show it at 50% opacity) before inputting text

**Comment by s-cheng** [comment]
@agnesstenlund You see the ad in the RHS but not on the post page? That means you must be in the wrong A/B test group - can you check that? (I'd really like you to test out how the UX feels and let me know if you have any feedback on that)

**Comment by agnesstenlund** [comment]
how do I check that I'm in the right A/B test group? 😮

**Comment by agnesstenlund** [comment]
looks great, made some small tweaks 🙏 
Screenshot 2024-02-12 at 14 32 04
Screenshot 2024-02-12 at 14 32 24

**Comment by s-cheng** [comment]
@agnesstenlund looks great, thanks so much!

**Review by Will-Howard — APPROVED** [review]
LGTM as far as the code is concerned

**Pull request merged**
