### PR TITLE
deploy group banner image

### PR DESCRIPTION
**Pull request by s-cheng**

### CODE REVIEW

**Comment by jpaddison3** [comment]
> hide frontpage review widget for logged out view

Wait, this is a thing? I'm skeptical

**Comment by jpaddison3** [comment]
Hmm, let me think. .... I think I disagree? I'm sorry I missed that, I assume it came with the book stuff.

**Comment by s-cheng** [comment]
@jpaddison3 Sorry I thought we had the same homepage component as LW, but their change doesn't affect us

**Comment by jpaddison3** [comment]
I was also on a call, now am off a call. Cool, seems good.

**Pull request merged**
