### PR TITLE
Add a special-case error message if signing up with an existing email

### PR DESCRIPTION
**Pull request by oetherington**
Currently, if you try to sign up for an account with an email address that is already used by another account you get a very unhelpful "Invalid signup" error message. This PR adds a special case to instead show "A user with this email already exists".

Screenshot 2024-03-12 at 19 53 08

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206825549006658) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by s-cheng** [comment]
@oetherington Just checking, have you seen [this](https://support.auth0.com/notifications/5d2cb6209db665000aed8695?_ga=2.36293856.1169584547.1612177227-1595415333.1607347674&_gl=1*1bhwa4d*_gcl_au*MTE3MTkwNTU4NS4xNzA2NjM4NDMz*_ga*MTA1MTY0MjIzMi4xNzA2NjM4NDMz*_ga_QKMSDV5369*MTcxMDI3OTk4Ny4zLjEuMTcxMDI3OTk5Ni41MS4wLjA.)?

**Comment by oetherington** [comment]
@s-cheng Oh, I was not aware of that.

After looking into it, I think I'm still tempted to do it in the code this way and leave the setting as it is:

- This way we don't affect GWWC/any other users of the same tenant
- If someone tries to brute force the public Auth0 API from a script then we'll still have that protection in place

It's not a particularly strongly held opinion (I think both those arguments are quite weak), so let me know if you think there's any reason we should actually just disable the setting and close this PR.

**Review by s-cheng — APPROVED** [review]
@oetherington Yeah I feel unsure about this. I don't think we should change the setting in Auth0. I'm mostly unsure if we should make this change at all - I think it would be better to make the message sound more generic and just suggest that they try logging in, but I can't think of a succinct way to say that right now, so this seems good 👍

**Comment by oetherington** [comment]
Makes sense. I'll merge for now, but I added a ticket to asana to think about it more in the future.

**Pull request merged**
