### PR TITLE
[LW Only] Slightly improve /books/2019, and redirect /books to it

### PR DESCRIPTION
**Pull request by Raemon**
This commenter just told everyone about our secret /books/2019 page. I think the page is okay but not great, and I wouldn't go out of my way to link to it (it seemed like Oli/Ben made a conscious decision to focus on the book announcement post instead?) but seems like we might as well have /books point to it now.

Pr also cleans up some minor styling issues.

https://www.lesswrong.com/posts/mvPfao35Moah8py46/book-launch-the-engines-of-cognition?commentId=8rNGvy9S7EJ53aT6z#comments

### CODE REVIEW

**Comment by jpaddison3** [comment]
I checked this out and viewed it locally. I don't think this is what you wanted, bug probably not visible to you because you're in the US:

image

**Comment by jpaddison3** [comment]
Scrolling down and scrolling up leads to dueling headers:

image

Probably not due to you though.

**Review by jpaddison3 — DISMISSED** [review]
Found some bugs, but I trust you to resolve or ship to your satisfaction.

**Comment by jpaddison3** [comment]
[Meta]

* As mentioned in the slack post, this is a review performed because we say we'll do reviews, not out of selfish desire to improve the code quality of the EA Forum. You're welcome to get @darkruby501 or someone else to review these PRs if you want, but we'll always be available for PR review otherwise.
* Sorry for the delay in review, it's easy for things to slip through the cracks during holidays.

**Comment by Raemon** [comment]
I think it makes sense for reviews that are LW specific UI changes to get reviewed by ruby, since a lot of what needs reviewing here is the overall aesthetic decision for LW.

**Pull request closed without merging**
