### PR TITLE
fix build script... again

### PR DESCRIPTION
**Pull request by b0b3rt**
@jimrandomh for later, in case you have a cleaner way of doing this

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204718641762303) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by Raemon — APPROVED** [review]
I don't think I've thought through all the ways this could subtly fail, but have talked it through with Robert, and it seems at least unlikely to fix the part where deploy wasn't working at all and _then_ break afterwards in a way that takes down the site. But, meanwhile we'll make sure to be ready to rollback the deploy if something goes wrong.com

**Comment by b0b3rt** [comment]
Actually yeah this might not even work, I don't think there's a `.ssh` directory in our Docker container (& so I'm not sure if SSH tunneling would work for prod at all).  Does SSH tunneling in prod even help?

**Comment by jimrandomh** [comment]
Hang on, I think we probably don't actually want prod to try to use the ssh tunnel; the benefit comes from the dev-machine-to-datacenter connection. Also, I'm still flying, so I won't be available to help if this brings down prod.

**Comment by jimrandomh** [comment]
Note that the site itself does _not_ use an SSH tunnel. It's only development macines and github action runners.

**Review by jimrandomh — APPROVED** [review]

**Comment by jimrandomh** [comment]
It might be slightly better to put the host key into the config file, or to find an ssh command line option to skip the host key check. I think this method is fine, though.

**Comment by jimrandomh** [comment]
Wound up failing because `~/.ssh` doesn't exist on the runner. Will fix.

**Pull request merged**
