### PR TITLE
Visited link new color

### PR DESCRIPTION
**Pull request by Raemon**
So I was gonna have my second color option be "some kind of green" but man I just really think all the greens suck. They either look sickly yellow or are even lower contrast than the other grey one or are weird neon that is also not actually a good contrast.

So I ended up just finding a grey that's in-between grey[500] and grey[600] (which was barely distinguishable). The contrast ratio here is 3.45 (compared to the previous one's 2.67).

image

### CODE REVIEW

**Comment by b0b3rt** [comment]
What does it look like in dark mode?

The visited-green I've been poking at are b1d9b5 (light mode) and 91ba95 (dark mode), but this is in contrast to the original green (5f9b65), not the new one.  They are lower-contrast than the greys but seem... ok?

(light mode image didn't go through bc github)

image

**Comment by Raemon** [comment]
Here's what the specified green looks like in light mode. I think this is too low contrast, although agree it looks good in dark mode.
image

**Comment by Raemon** [comment]
Here's what the darkish-grey color here looks like in dark mode:

image

**Review by oetherington — COMMENTED** [review]
No objections from EAF

**Comment by Raemon** [comment]
Hmm, well I just realized the text needs to be able to handle cases like this (not super common, but happen occassionally)

image

So here's a version with _slightly_ darker text, which I think is the max you can do before it's too similar to the black.

image

Here's a version where I give the grey text a very faint green, which I think might help it be a little more distinguishable:

image

**Comment by Raemon** [comment]
After chatting with Oli, ended up with this, which IMO is too similar but I'm happy to try out for awhile.

image

**Review by Discordius — APPROVED** [review]

**Pull request merged**
