### PR TITLE
[EA] Smaller text and sans serif for tables

### PR DESCRIPTION
**Pull request by oetherington**
As requested on Slack - exact values might want tweaking.

Before:
Screenshot 2024-01-19 at 23 10 38

After:
Screenshot 2024-01-19 at 23 10 11

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206396142574760) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by oetherington** [comment]
FYI @agnesstenlund

**Comment by agnesstenlund** [comment]
This is so much better, thank you 🙌 

- [ ] while we're at it–could we make the padding inside of the table the same both vertically and horizontally? Looks like it's slightly more on top than to the left here (think the top is better, more space to breath):

Screenshot 2024-01-22 at 13 23 20

The bullet list also has a bunch more padding than normal text (is this easy to change?). Think it should have a bit more, but not _that_ much more.

- [ ] also looks like the line-height is pretty big on the non-list stuff, probably inherited from the bigger font size? Would make that tighter

Screenshot 2024-01-22 at 13 24 55

**Review by jpaddison3 — APPROVED** [review]
Code seems fine, ASTLAC wrt Agnes's comments

**Comment by oetherington** [comment]
@agnesstenlund How's this?

Screenshot 2024-01-24 at 14 45 42

**Comment by agnesstenlund** [comment]
Nice! Made some small changes. 

The ol and ul still has a bit much space IMO, would cut in half 
Screenshot 2024-01-25 at 12 58 09

On this table the padding also doesn't seem to apply, I'm nots sure why? 😮 
http://localhost:3000/posts/Jx6ncakmergiC74kG/deference-culture-in-ea

Screenshot 2024-01-25 at 12 31 51

Another thing that's not directly related to this but I think the default here should be top-aligned, not centered:

Screenshot 2024-01-25 at 12 53 17

**Comment by jpaddison3** [comment]
Probably the BW problem should be a separate ticket.

**Comment by oetherington** [comment]
@agnesstenlund I just decreased the padding:
Screenshot 2024-01-26 at 18 31 08

The padding isn't applied in the "Deference Culture in EA" post because it's overridden in the HTML - I'm not sure how that happened (probably some setting in CKeditor that's has since changed).

I think changing the default alignment should probably be a separate ticket (I just added it to Asana).

I added `word-break: normal` which should fix the wrapping in Ben's post. It's a slightly risky change though, so we should keep an eye on it and be prepared to revert if it breaks other stuff.

**Pull request merged**
