### PR TITLE
Make checkbox labels clickable

### PR DESCRIPTION
**Pull request by michaelkeenan**
(This is an unsolicited and not-previously-discussed PR to solve a thing that bugs me; hope that's not too annoying. I'll not be offended if this is not deemed worthwhile to review or merge.)

Most LessWrong/EA/etc. checkboxes don't toggle when you click their labels. It'd be a minor usability gain if they did, and HTML has native support to enable that by having two ways to associate a label with its checkbox:

1. specify the checkbox's id in the label's `for` attribute, or
1. nest the checkbox inside the <label> element.

(For a quick example of this being associated correctly, click on the Remember Me label or Use Token label at https://secure07ea.chase.com/web/auth/dashboard#/dashboard/index/index)

(also see https://uxmovement.com/forms/why-your-checkboxes-need-to-have-label-tags/)

Unfortunately, VulcanJS uses neither of these methods. Ideally, I'd alter VulcanJS form code to make it associate the labels correctly, but that seemed difficult, so instead I just replicate it with a JavaScript event listener, in clickableCheckboxLabels.ts. (This is not a perfect replacement; there are other advantages to setting the association correctly, such as screen readers describing them better.)

This applies only to checkboxes in forms generated by VulcanJS from collection schemas. Other checkboxes, for which we write the code ourselves, should use one of the two HTML ways to associate with labels correctly, so this PR also changes some of those to associate them the usual HTML way. Specifically, these four:
-The "These users have agreed to co-author this post" checkbox on the new post at /newPost
-The "Moderators may promote to Frontpage" checkbox at the bottom of the new post page at /newPost
-The "Notify me when there are {peopleThresholdInput} or more people in my area" checkbox when you've clicked "Subscribe to events" to open the modal at /community
-The "Show negative karma notifications" checkbox in the Notifications section of the Account Settings page at /account

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204359092838131) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by Raemon** [comment]
(We'll take a look at this sooner or later but are busy atm)

**Comment by michaelkeenan** [comment]
No hurry! :)

**Review by s-cheng — APPROVED** [review]
@michaelkeenan Thanks! This issue was quite annoying to me personally and I appreciate your improvements to the forum. :)

I'm not sure if you can merge this in yourself - feel free to do so after addressing my comments, or let me know if you can't and I can take care of it.

**Comment by michaelkeenan** [comment]
Sorry it took so long to get to this! I was going to do this today, but I'm having dev setup problems (due to the postgres change, I think), so it'd be easier if you take care of it. On looking at the code, I agree that checkboxContainer being used twice in CoauthorsListEditor.tsx is weird, and I'm not sure what I was thinking with that. Splitting it into separate classes would make sense.

**Comment by jpaddison3** [comment]
@michaelkeenan, you may be interested in [this PR](https://github.com/ForumMagnum/ForumMagnum/pull/7515)

**Comment by michaelkeenan** [comment]
I've finally gotten back to this (thanks JP for getting me set up with postgres).

The new commit makes these changes:
- In CoauthorsListEditor.tsx, it splits the checkboxContainer class into checkboxContainer and checkboxLabel, as Sarah suggested.
- In SignupSubscribeToCurated.tsx, it makes the Subscribe To Curated Posts checkbox clickable.
- It adds cursor: pointer to a few of the ones I'd made clickable earlier, but had neglected to add that class.

**Review by s-cheng — APPROVED** [review]
Thanks so much!

**Pull request merged**
