### PR TITLE
[EA Forum only] add icon for closing the left menu

### PR DESCRIPTION
**Pull request by s-cheng**
This PR adds a new icon that displays in the left side of the site header when the left menu is open. This is to help communicate to users that clicking it will close the menu rather than open another menu.

Screen Shot 2023-06-27 at 11 20 51 PM

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204922029100571) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by agnesstenlund** [comment]
thanks for doing this!!

seeing this I'm realising we have to change the other icon too, since they have different border radiuses + spacing

https://github.com/ForumMagnum/ForumMagnum/assets/13235378/7e13f9c2-9627-4718-ba92-37b423e2da82

when the screen is at 100% parts of the icon also looks a tiny bit blurry–which is fully my bad and probably related to half-pixels I've added or something like this. I'll tweak and export new ones 🙏

**Comment by agnesstenlund** [comment]
try these–may still be blurry 🤞 

hamburger-collapse
hamburger

**Review by oetherington — APPROVED** [review]
👍 Looks good

**Comment by oetherington** [comment]
@s-cheng Sorry! I just accidentally pushed a couple of commits to this branch that should have been on a different branch. I force-pushed it back to (I think) the right commit.

**Comment by s-cheng** [comment]
Thanks @agnesstenlund! ^^ I've updated this branch with the new icons, they seem good to me (I recorded a short video of toggling them):
https://github.com/ForumMagnum/ForumMagnum/assets/9057804/4edcd6cb-4180-4c47-972d-2d05aea3422e

**Pull request merged**
