### PR TITLE
Fix unit test memory leak

### PR DESCRIPTION
**Pull request by jimrandomh**
The out-of-memory errors in unit tests were caused by two separate issues each of which leaked lots of memory, adding up to just barely reach the threshold of where things would fail (by increasing slightly every time we added more tests, until it started breaking so we noticed it). The first is https://github.com/facebook/jest/issues/10550, which leaks about 50MB per test file (about 1GB total). The second was a double-initialization of `jest-mongodb` which leaks a subprocess and some metadata with each test file (about 200MB total).

There is no proper fix for the Jest module caching leak, but downgrading from nodejs 15+ to nodejs 14 is an effective mitigation which reduces the size of the leak by an order of magnitude. So I've changed the nodejs version in `.github/workflows/unitTests.yaml`. Peak memory usage is still O(n) in codebase size and in number of test files, which will eventually become a problem, but hopefully by then it will have been fixed upstream.

### CODE REVIEW

**Comment by jpaddison3** [comment]
I'm nervous about changing the node version only on tests. I'm worried about it causing a situation where we do something that's ok in our development environment, and then tests fail on CI only, don't fail locally, and a dev who wasn't familiar with this PR being incredibly confused.

What's the harm in downgrading to 14 across-the-board? It doesn't look like 15 has that much going for it over 14, and 14 is Long-Term-Stable.

**Comment by jpaddison3** [comment]
Otherwise very appreciative for the fix to our unit test sadness.

**Review by s-cheng — APPROVED** [review]
I agree with JP, kind of nervous about the version change, but also I'm not sure how much that matters. Thanks for fixing this! :)

**Comment by jimrandomh** [comment]
I do agree that differences between prod and test are generally bad and to be minimized, so we might consider downleveling prod from 15 to 14. That's a lot riskier than downleveling test, though, so if we do it it should be a separate change with a bit of testing. And test being stuck at 14 should be temporary, until https://github.com/facebook/jest/issues/10550 is resolved.

**Comment by radcapitalist** [comment]
I can confirm for my project that downgrading Node from 16.13 to 14.15 greatly mitigated the unit test leak. Our unit tests (81 test files) were able to complete with Node 14.15.  With Node 16.13, we only get through 20 test files before the JavaScript heap is out of memory.

**Pull request merged**
