### PR TITLE
Exploring fonts: New serif, more line-height, smaller headings, more padding for post items etc.

### PR DESCRIPTION
**Pull request by agnesstenlund**
Trying this out for overall improved legibility. Would love feedback :pray: 

Changed:

* Serif we use
* Line-height and font size on post pages to increase legibility
* Slightly smaller headings on pots
* Gave postitems slightly more padding to make them breath more + hopefully increase legibility

**some before and afters**
Screenshot 2023-08-15 at 15 24 19
Screenshot 2023-08-15 at 15 24 31
Screenshot 2023-08-15 at 15 24 41

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1205277342310037) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by SharangP** [comment]
I'm a fan of the the first three changes, I'm least sure about the postitem change (though I kinda suggested it). It might be helpful to see that last image with the exact same posts and the same read/unread status. Would be good to get @jpaddison3 and @s-cheng 's opinions on this too

**Comment by jpaddison3** [comment]
JK, you are downloading it, I dunno what the issue is.

**Review by Will-Howard — APPROVED** [review]
ASTLAC, I've fixed the font downloading issue. I really like how the new font + lower weight looks on widgets and stuff, the library page looks so much better imo (after, before):
Screenshot 2023-09-05 at 17 51 52
Screenshot 2023-09-05 at 17 53 39

I do agree with JP that the size + line height is too big in post bodies though, even with the slightly reduced line height. I think it makes it feel less "newspaper/journal"-ey

**Comment by agnesstenlund** [comment]
Thanks so much @Will-Howard! Really appreciate it

**Comment by agnesstenlund** [comment]
just noticed some other fonts have changed in size too (see author, date, etc.) –will just fix that before merging
Screenshot 2023-09-06 at 13 12 38

Screenshot 2023-09-06 at 13 12 41

about the line-height still feeling too large I'd be in favor of shipping this and seeing how it feels, and if it still feels too large and non-journaly after a few days/weeks we should decrease it a bit.

**Comment by Will-Howard** [comment]
@agnesstenlund I just noticed the images in the library page are now overflowing, this is because they are picking up the new font size from `basicText` when previously they used the default size set by the browser
Screenshot 2023-09-07 at 11 53 16

I'm not sure what we want to do about this, but maybe applying the font size lower down in the hierarchy would reduce the risk of changing things by accident. I've marked styles this might affect with this message: `// TODO-wh this may now be getting fontSize: "1.35rem" from postStyle when there was previously no size applied` to make them easier to find

**Comment by agnesstenlund** [comment]
Thanks a lot @Will-Howard 🙏 took a look at this again and moved the fontsize further down in the hierarchy like you recommended. I also changed it down to 1.3 (instead of 1.35).

I think this could be cool to merge together with all other september features

**Comment by agnesstenlund** [comment]
there is now much less of a difference
Screenshot 2023-09-26 at 12 05 07

**Comment by agnesstenlund** [comment]
[Let's hold off on merging this for a few days]

**Pull request closed without merging**
