### PR TITLE
[EA] Add new tag info box

### PR DESCRIPTION
**Pull request by oetherington**
Adds an info box to the new tag page for EA forum.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207941281084056) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by oetherington** [comment]
@agnesstenlund This is a request from Toby - I'm interested in your input. My initial feeling is that it's too much text and people won't bother ready it - maybe you have ideas?

Screenshot 2024-07-31 at 12 07 26

**Comment by oetherington** [comment]
Shorter copy update from Toby:

Screenshot 2024-07-31 at 12 24 11

**Review by Will-Howard — APPROVED** [review]
Screenshot 2024-08-02 at 10 42 45
There is a screen width where it overflows, otherwise looks good 👍

**Comment by agnesstenlund** [comment]
Nice, I like the shorter version! 

We could cut the "Adding a new topic" header/ replace it with: "Your topic may be reject if"? 

Would also underline the link so it's easy to spot in light mode too.

**Pull request merged**
