### PR TITLE
Giving season 2024 voting portal

### PR DESCRIPTION
**Pull request by oetherington**
Voting portal for 2024 giving season. [Relevant figma](https://www.figma.com/design/3WOTZHH10ZBXSZPWw9omM3/Giving-Season?node-id=1611-2021&node-type=text&m=dev).

The page is located at `/voting-portal`.

Heavy inspiration taken from #8305 and #8622.

Screenshot 2024-11-17 at 18 23 50
Screenshot 2024-11-17 at 18 24 06
Screenshot 2024-11-17 at 18 24 16
Screenshot 2024-11-17 at 18 24 31

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208768815743164) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by oetherington** [comment]
@agnesstenlund

**Comment by agnesstenlund** [comment]
This looks really great, the UI when dragging is really nice but the UX is a little confusing

- [ ] Would it be possible to make the whole row draggable instead of only the icon? Would also be great if clicking on the row would move it up instantly. I was thinking an interaction like [this](https://tally.so/help/ranking) (incl. the hovers etc.). If it's not possible to make the whole row draggable (and hoverable) we should probably use a different icon and maybe move it to the right (but ideally the whole row draggable, I think that's the most user friendly option).

- [ ] With the comment automatically getting published to the thread, I'm realising we should make it eeeeven more clear that this will in fact be published in your name. I'm thinking a design like this (+ updated copy)
Screenshot 2024-11-17 at 20 17 21

**Comment by agnesstenlund** [comment]
A few smaller things:

- [ ] You shouldn't be able to "Continue" if you haven't voted for anybody. The button should be unclickable and at 50% opacity. (Same with the "Comment" button)

- [ ] This section should be as close to the top as the one on the previous page (right now it feels like it sits too low down on the screen)

**Comment by Will-Howard** [comment]
I'm beginning to review the code now, one thing I noticed when testing my own branch is that you can't scroll down to vote for the last couple because they are covered by the bottom banner


https://github.com/user-attachments/assets/0d029c59-e144-4c67-8d36-e0eb18246aa9

**Comment by agnesstenlund** [comment]
This looks really great, thanks @oetherington for all the fixes! 👏 👏 

I may tweak the copy slightly after checking with Toby (+ would also like the top margin thing to change for the comment step) but think it's good to merge now (and we can tweak those after) 👍

**Comment by agnesstenlund** [comment]
(I haven't QAd if the voting goes through and comments work, but design wise this is great now 👍 )

**Pull request merged**
