### PR TITLE
DM page polish 💅 Decreasing font sizes + padding

### PR DESCRIPTION
**Pull request by agnesstenlund**
**Before**
Screenshot 2023-11-21 at 10 05 52

**After**
Screenshot 2023-11-21 at 10 14 05

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206000542596820) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by agnesstenlund** [comment]
Actually there may be cases where you've changed the title of the conversation + only a few of the participants are writing. In that case you'd need to find a way to see who's in the conversation. And since we don't have a general "info" section/button lets just keep that participant row for now

**Review by s-cheng — APPROVED** [review]
🦭

**Comment by s-cheng** [comment]
@agnesstenlund I'm not sure if you normally merge in your own PRs, but feel free to tag me if you want me to do it :)

**Comment by agnesstenlund** [comment]
I sometimes merge them but haven't deployed any, but that seems to happen magically anyway 😅 🪄

**Pull request merged**
