### PR TITLE
CKEditor footnotes

### PR DESCRIPTION
**Pull request by jcmustin**
This PR adds footnote support to CKEditor. (Note: this PR predated Forum Magnum, and has already gone through review within CEA [here](https://github.com/centre-for-effective-altruism/EAForum/pull/235).)

Footnotes can be added in two ways:

- via the popup toolbar, when content is selected 
- using markdown syntax (`[^<number>]`), which gets auto-converted to the same format as the above methods
Footnotes are indexed 1 to n. Deleting a footnote renumbers subsequent footnotes and their references. Reordering footnote references in the post reorders footnotes in the footer (s.t. the first footnote reference always has index 1).

See [the README](https://github.com/ForumMagnum/ForumMagnum/blob/940827e74a9ef319bc0992f7c5aa7cabd5ab794d/public/lesswrong-editor/src/ckeditor5-footnote/README.md) for a more thorough description of functionality and specifics about the code.

### CODE REVIEW

**Comment by Raemon** [comment]
I tested this out. When I select a word, and click "add footnote", it seems to insert the footnote indicator at the beginning of the word rather than the end, which is what I'd expect and want.

**Comment by jcmustin** [comment]
> I tested this out. When I select a word, and click "add footnote", it seems to insert the footnote indicator at the beginning of the word rather than the end, which is what I'd expect and want.

Thank you! Fixed in 940827e74a9ef319bc0992f7c5aa7cabd5ab794d.

**Comment by darkruby501** [comment]
Very cool! This is one of the most requested features, so I'm very glad to see this being shipped. Thanks.

Thoughts:
- My understanding is that the side toolbar is for block/paragraph level things, which this isn't it. So both for conceptual reasons and for reasons of redundancy, I'd remove it from the side/block menu and only have it for the pop-up select-text menu.
- It would be super cool and I think worth delaying this to introduce hover-over preview for footnotes.

**Comment by jcmustin** [comment]
> * My understanding is that the side toolbar is for block/paragraph level things, which this isn't it. So both for conceptual reasons and for reasons of redundancy, I'd remove it from the side/block menu and only have it for the pop-up select-text menu.

That makes sense! Removed from the block toolbar in 45a1fad0ac87065b4d3fc7efd8b64d916fb126c9.

> It would be super cool and I think worth delaying this to introduce hover-over preview for footnotes.

Added in 48b01de5efbcbb8a814e9c446eb561619c9cabd8 🙂

**Review by jpaddison3 — APPROVED** [review]
LGTM (already reviewed in old PR)

I would make sure to double check that the transpiled code is up-to-date before merging.

**Pull request merged**
