### PR TITLE
Tagging on post new/edit form

### PR DESCRIPTION
**Pull request by Raemon**
This allows authors to tag their post before they publish this. I'm hoping this a) streamlines some work from moderators, reducing how much time we have to spend tagging new posts, and b) allows tag-filtering to work more reliably (some people complained that even though they have AI posts set to "hidden", they still end up seeing a bunch every day because it's often several hours before a moderator ensures the post is tagged properly.

Some less obvious things:

A) This bundles "CoreTagsChecklist" into "FooterTagList", so that they use one unified UI. I already had found CoreTagsChecklist + FooterTagList a somewhat annoying UI for the sunshine sidebar, and would expect users who're self-tagging to also find it annoying.

B) The tag list appears in the custom form-submit component, because that's the only way I could get it listed _above_ the submit button, and it felt awkward for it to be below the submit button.

C) You can't actually create tags for on a "new" post edit form, because the post doesn't exist yet, and doesn't have an _id. So instead, I create a dummy component that, when you click on it, saves the post and switches you over into the editor-view (similar to how sharing a post works)

D) To get 'C' to work, I had to pass the 'submitForm' function into 'getFormSubmitProps'. Weirdly, the form-submit component doesn't automatically have access to this, in either the props or the context (I guess it relies on some html magic? Robert and I both looked at this and were pretty confused, if I missed something here and should wire this differently let me know)

image

### CODE REVIEW

**Comment by s-cheng** [comment]
@Raemon FYI: https://github.com/ForumMagnum/ForumMagnum/pull/5664

I do like your design better, as I wasn't happy with our attempts to combine the two components we used for selecting tags. I think we should combine our solutions somehow, or maybe we should post in slack to hear others' thoughts on how this feature should work.

**Comment by Raemon** [comment]
Oh, I totally missed that PR. Whoops about the duplicate effort.

**Comment by jpaddison3** [comment]
Motion to convert this PR to a draft

**Comment by Raemon** [comment]
Sarah's notes from slack:

TBH I’m not super happy with either of the PRs. Ray’s UI is much nicer, and I think I prefer it enough that I’d go with that PR, but here are some changes I’d like to see:

I quite dislike that clicking on a tag in a new post saves the post and refreshes the page. Maybe if it just saved in the background it would be better. But I still prefer our solution that preserves the current saving behavior.

I also noticed a bug where clicking on a tag to save my new post didn’t actually apply the tag to the post, though I thought 

I remember this working at some point. I also see some console errors, probably related.
We shouldn’t show special tags in the editor (ex. “Frontpage”).
Clicking on a tag that is already applied should not route you to the tag page, since you lose any changes you made in the form.

I would maybe hide this on mobile entirely, since practically speaking, you can only add tags and not remove them (so you can’t undo a misclick).

I think it’s buggy on mobile anyway… adding a tag doesn’t quite work and I saw some console errors.
Reminder to use the config setting for the tagging name - EAF should say “Post Topics”.

**Comment by Raemon** [comment]
Reflecting a bit more, I ended up making a new branch which merges this branch and Jim's, since I needed basically all the pieces.

**Pull request closed without merging**
