### PR TITLE
[EA] People directory topics

### PR DESCRIPTION
**Pull request by oetherington**
Adds a "topics" column and filter to the people directory. [Figma](https://www.figma.com/design/qAHRGADVOGojqKpqbGMFFu/2024-Q2?node-id=936-10038&m=dev).

Because we change the type of the `tags` column in the `users` index in a way that is incompatibly with the old mapping we unfortunately need to manually delete and recreate the entire index which is a bit annoying, but it takes <1 minute, so should be fine:
```
./scripts/serverShellCommand.sh "Globals.elasticDeleteIndex('Users')"
./scripts/serverShellCommand.sh "Globals.elasticConfigureIndex('Users')"
./scripts/serverShellCommand.sh "Globals.elasticExportCollection('Users')"
```

Screenshot 2024-06-19 at 09 34 13

Screenshot 2024-06-19 at 09 34 20

Screenshot 2024-06-19 at 09 34 53

Screenshot 2024-06-19 at 09 35 04

Screenshot 2024-06-19 at 09 35 25

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207600870067573) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by agnesstenlund** [comment]
This looks perfect, thank you <3 

this is a side-note, but I'd steal a bit of space from the bio (maybe a bit from the name too) and give to "career stage" which is starting to look pretty cramped. Also hide "profile last updated" by default

**Comment by s-cheng** [comment]
@oetherington Sorry for the delay! Playing around with it now and the topic filter doesn't seem to be working for me? Whenever I add a filter it says there's no results.

Also a small bug I noticed: when adding columns, the "+ more" seems to disappear:

https://github.com/ForumMagnum/ForumMagnum/assets/9057804/b0ee07cb-0b0a-4858-8569-271a2fa8b149

**Comment by oetherington** [comment]
@s-cheng Whoops - sorry, was broken in the last change I made. Should be working again now.

**Review by s-cheng — APPROVED** [review]
LGTM! The main issue is that the logic around truncating the tag list in the cell is kinda buggy. Personally I would simplify it (don't worry about how many lines it takes, just limit it to 3 tags), but feel free to make it fancier. :)

Also only slightly related (def not a blocker for this PR): I prefer that search pages like this store the filter/sort state in the URL, so that if the UI is buggy and I refresh the page, it remembers all my filters/sort order. Right now we only seem to remember the keyword text, so it's a bit weird that it's inconsistent. @agnesstenlund FYI

**Comment by agnesstenlund** [comment]
Small addition! Could we add the number of topics here so it's clear there's more than just the ones in the list?

`So like "Search 2932 topics"`

Screenshot 2024-06-24 at 13 39 43

**Comment by oetherington** [comment]
@s-cheng Should be tidied up now. For now I've just set it to only show 2 tags and "+ n more", with a line limit of 2. If the two first tags have really long names then it's possible the "+ n more" may wrap onto a third line and be hidden, but I'm not sure fixing that is worth delaying further. It's probably best to just leave it for now and wait to check if Agnes has any better ideas.

Screenshot 2024-07-11 at 12 55 49

**Comment by s-cheng** [comment]
@oetherington Nice thanks! I agree that it's best to just ask @agnesstenlund once she returns.

**Pull request merged**
