### PR TITLE
Add noindex meta tag to posts pages for posts with karma <=0

### PR DESCRIPTION
**Pull request by oetherington**
This PR adds a "noindex" meta tag to the posts page for all posts with 0 or less karma.

Originally I'd planned to add callbacks to set the `noindex` field to true when dropping below 1 karma, or false when rising above 0 karma, but there's a few problems with this:
 - It seems unnecessarily complex
 - Race conditions could lead to mistakes
 - If a post with positive karma has "noindex" manually set to false, then it drops below 0 karma, then it rises above 0 karma again, "noindex" will be automatically set to true. We could just add a second field like `automaticallyNoIndex` but, again, this just feels like unnecessary complexity.

One downside of this approach is that queries that check for "noindex" might now miss these posts in certain circumstances, but in practice I think anywhere where we do this kind of filtering already considers karma separately.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208378807943161) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by oetherington** [comment]
@b0b3rt This is not currently forum-gated - let me know if you'd like it to be

**Review by Will-Howard — APPROVED** [review]
> Originally I'd planned to add callbacks to set the noindex field to true when dropping below 1 karma, or false when rising above 0 karma

Did you think about making it a resolver only field? I think this would be slightly better than checking on the frontend, although there would still be a few more steps to be able to e.g. select on it.

Anyway LGTM, happy for you to merge this as is

**Comment by b0b3rt** [comment]
My current guess is that LW doesn't want to noindex those posts, though curious what the motivation here is.  Does there actually turn out to be a lot of traffic from people landing on low-quality posts via organic search results?

**Comment by oetherington** [comment]
@Will-Howard Thanks! I think I'm just going to leave it as-is for now, just because I think it's a bit of a hack either way so I'd rather keep the footprint as small as possible

**Comment by oetherington** [comment]
@b0b3rt I think @s-cheng can chime in on motivation?

**Comment by s-cheng** [comment]
@b0b3rt I don't think there's a lot of traffic from negative karma posts, but someone did report this to us so maybe they encountered it. In general I think that a negative karma post is a sign that the post is not a good fit for the Forum, and so it doesn't make sense to associate it with the Forum on search engines.

**Pull request merged**
