### PR TITLE
Add "Comment Icon" for Users Awaiting Review

### PR DESCRIPTION
**Pull request by darkruby501**
LessWrong is enabling review-required for new user's first comments. To go with this, we've added a comment icon in the same places that there's a post icon, to help us prioritizing reviewing users with new comments.

We've also added sorting to put these users higher up.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204334528936103) by [Unito](https://www.unito.io)

Moderation Dashboard - LessWrong 2023-04-04 13-29-25

Moderation Dashboard - LessWrong 2023-04-04 13-29-48

LessWrong 2023-04-04 13-30-25

### CODE REVIEW

**Comment by darkruby501** [comment]
@jpaddison3 Do you want these changes too?

**Comment by jpaddison3** [comment]
I wondered if you'd turn that setting on. I assume you mean `hideUnreviewedAuthorComments`? These things seem sensible to me, but screenshots are always nice.

One thing to check is whether any of this does _not_ apply if that setting is _dis_abled. I think all of it is still useful. Can you post in the shared channel with moderators before you ship it to let them know about the change to their tooling?

**Comment by jpaddison3** [comment]
Related issue: https://github.com/ForumMagnum/ForumMagnum/issues/6900

**Comment by jpaddison3** [comment]
Also related: https://github.com/ForumMagnum/ForumMagnum/issues/6901

**Comment by jpaddison3** [comment]
I think I understated earlier how happy I am to have these actually. These seem freaking great. Thanks a bunch for building this.

**Review by b0b3rt — APPROVED** [review]

**Pull request merged**
