### PR TITLE
Read from DatabaseMetadata in Postgres

### PR DESCRIPTION
**Pull request by oetherington**
DatabaseMetadata has a quirk where we need to be able to read from it during server startup before the collections have been fully initialized, which means reads are done directly through the databsae rather than through the collection. This means that we're still reading from Mongo after already migrating to Postgres. This PR fixes this issue.

Note that this should still be backwards compatible for LessWrong who are still on Mongo.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203938654862302) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by s-cheng** [comment]
@oetherington Not sure what's wrong - the page loads fine, but when I click on anything it looks like it loses access to the db settings. For example, the search bar gets replaced with the message "Search is disabled (Algolia App ID not configured on server)"

**Comment by oetherington** [comment]
@s-cheng Whoops - sorry about that! It should be fixed now. It was caused my frontend components importing server code that in turn imported the code that updates the settings cache, but there's no Postgres connection on the frontend so it just cleared the cache...

**Review by s-cheng — APPROVED** [review]
Thanks for fixing that! :D

**Comment by jimrandomh** [comment]
This PR brought down LW when we deployed it

**Pull request merged**
