### PR TITLE
added 'bet' reacts, removed 'verified' reacts

### PR DESCRIPTION
**Pull request by ben-pace**
Added two new reacts, replaced them in the two react palettes, left the code in for "I checked it's true / false" but removed them from the palettes.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208267799709000) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by Raemon — APPROVED** [review]

**Comment by rjmk** [comment]
Ronny says that "I would bet that something is true" is a heresy in the religion he was encultured into by LessWrong

**Comment by Raemon** [comment]
wuckles

**Review by oetherington — COMMENTED** [review]
No objection from EAF - CI should be fixed now if you merge master

**Review by b0b3rt — APPROVED** [review]
If we're deprecating `verified` and `verifiedFalse`, we should probably set `deprecated: true` on them.  (That'll prevent them from coming up in a search if a user manually searches for one of them.)

But if we're not, then this is fine.

**Pull request merged**
