### PR TITLE
Revert "add a day"

### PR DESCRIPTION
**Pull request by Raemon**
I'm not 100% sure what the intent of the "add 1 day to the phase-end-dates" thing was, but it seemed to mostly make things more confusing and cause the timeline to render weird. @jpaddison3 I think you added that, can you clarify what the intent was? 

I think it makes sense to revert, but if it was solving a particular problem that needs to be solved some other way let me know,

### CODE REVIEW

**Comment by jpaddison3** [comment]
So, according to me, this makes it more consistent with the labels in the UI, with the way people intuitively think about end dates, and works correctly except for: a slight (very fixable) bias in the progress bars, and an apparently error in exactly when LW cut over? I'm guessing the LW bug is related to some local machine parsing a date in local time somehow, and it would be a problem with or without the added day. I would recommend keeping the code.

If you _did_ want to remove the add day code, please please also remove the comments describing the behavior. And also please edit the UI to make the FrontpageReviewWidget consistent with the new behavior (it should be a very easy fix of using moment.subtract).

Did you notice you pushed a commit identical to this straight to master? Given this PR I think it was probably an accident? It looks like github does not prevent pushing for administrators, which is unfortunate. Stackoverflow recommends running this on your laptop to prevent it in the future: `git config branch.master.pushRemote no_push`

**Review by jpaddison3 — CHANGES_REQUESTED** [review]
See comment on PR

**Comment by Raemon** [comment]
> Did you notice you pushed a commit identical to this straight to master?

Oh no, sorry about that. I noticed that immediately and then attempted to revert it, but I guess failed to do that.

**Comment by Raemon** [comment]
I've removed all instances of .addOne. It seems like the original intent was JP having intuitions about how date formatting is supposed to work (inclusive vs exclusive). I don't know that I actually have a strong opinion on that for things formatted i.e. Jan 1 - Jan 15, Jan 15 - Feb 1, but for the time-progress-bars I have a pretty strong intuition that "Jan 1" should mean "it goes *up to* Jan 1"

We can do more user testing on how people like dates displayed, but I think the actual fix for a lot of this is adding more explicit "N days/hours remaining" warnings.

**Comment by Raemon** [comment]
Closed in favor of:https://github.com/ForumMagnum/ForumMagnum/pull/4583

**Pull request closed without merging**
