### PR TITLE
[EA Forum only] Read history page

### PR DESCRIPTION
**Pull request by s-cheng**
This is a simple page where you can view the last 10 posts that you've read. It was built during our recent hackathon. ~We didn't bother to link to it from anywhere, but you can see it via~ `/history`. Actually now you can reach it via your profile page. @agnesstenlund has a design for a future iteration, where we will overhaul the current Bookmarks page to be a "Saved & read posts" page, which will have tabs for your bookmarks, your read history, and your vote history.

Screen Shot 2023-04-26 at 1 24 10 AM

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204476019928843) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by Discordius** [comment]
This seems great! I've been wanting this for a while

**Comment by jpaddison3** [comment]
@Discordius Hackathon project 🙂

**Comment by agnesstenlund** [comment]
This is great! 😍  I tried copying the styles from the All posts page title onto this one, but realised it'd be much nicer if we could pull that title styling out of the All-posts page and into the general theme file instead. May also be unnecessary to do for this particular change when my only real goal was to change the color to `color: theme.palette.grey[1000]`, so we could just do that instead?

**Comment by s-cheng** [comment]
@agnesstenlund Yeah I would love for us to clean up our theme at some point. 👍  Since I expect this page will be temporary anyway, I'm just going to change the color for this PR.

**Review by Will-Howard — APPROVED** [review]
🦭

**Pull request merged**
