### PR TITLE
Upgrade ESLint version, add lint rule for unused imports, remove many unused imports

### PR DESCRIPTION
**Pull request by jimrandomh**
Upgrades ESLint to the latest version. Adds the `unused-imports` ESLint plugin. Removes lots of unused imports.

I believe we used to have a lint rule covering unused imports, but lost it in the JS->TS switchover.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1202732134981048) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by jpaddison3 — APPROVED** [review]
Thanks!

**Comment by jpaddison3** [comment]
> I believe we used to have a lint rule covering unused imports, but lost it in the JS->TS switchover.

I believe this was done by DeepScan, not eslint, and was lost when we dropped it.

**Comment by jpaddison3** [comment]
What in the hell is that cypress error about, rerunning.

**Comment by jpaddison3** [comment]
That cypress error seems novel and odd, I am confused.

**Comment by jimrandomh** [comment]
Cypress error was that some ESLint plugin specifically dislikes Node 15 (as opposed to 14 or 16+). I bumped the nodejs version number in the Cypress config (but not anywhere else) from 15 to 18.

**Pull request merged**
