### PR TITLE
Upgrade OAuth-related libraries, hopefully fixing Facebook login

### PR DESCRIPTION
**Pull request by jimrandomh**
Facebook login is currently broken in LessWrong production. In my incredibly janky test environment involving an apache forwarding server, a self-signed certificate and a `/etc/hosts` file full of lies, these version upgrades made the difference between being able to complete a login and not being able to. A more complete and representative test requires being on prod, though, so I'm merging to `lw-deploy` in advance of merging this PR to master.

### CODE REVIEW

**Comment by jimrandomh** [comment]
(This isn't adding a new dependency on `passport-oauth2`, it's just making an indirect dependency explicit, in order to be able to specify a minimum version number. I did not test to distinguish whether it was the upgrade to `passport` or the upgrade to `passport-oauth2` that mattered, but I saw stack-traces pointing into the latter.)

**Review by Discordius — APPROVED** [review]

**Comment by Discordius** [comment]
I do want to sanity-check that this didn't break any other type of login, since this is a pretty high-risk version upgrade

**Comment by jimrandomh** [comment]
@jpaddison3 or someone from the EA Forum side should check that this didn't break auth0 in particular, before this merges to master.

**Review by s-cheng — APPROVED** [review]
I tested that I was still able to log in locally, so I think it's good

**Pull request merged**
