### PR TITLE
Giving season 2024 post-election banner

### PR DESCRIPTION
**Pull request by oetherington**
See https://cea-core.slack.com/archives/C03G0AQ925P/p1732637687034919

- Add the "hidden" banner for the intermission weeks and update styles for previous weeks
- Close voting and donating for the election
- Disable scrolling between weeks (it doesn't work very well now that one of the weeks makes the banner disappear)

Note that you can't easily test this on the prod DB as it requires the correct forum event to be active, but it should work correctly already on the dev DB.

This PR is pretty messy - there's a lot of stuff commented out that could probably be deleted just because I'm not 100% sure exactly what we'll want to bring back for the remaining weeks later in December.

Screenshot 2024-12-03 at 14 49 40

Screenshot 2024-12-03 at 14 49 47

Screenshot 2024-12-03 at 14 49 54

Screenshot 2024-12-03 at 14 50 00

Screenshot 2024-12-03 at 14 50 09

Screenshot 2024-12-03 at 14 50 16

Screenshot 2024-12-03 at 14 50 32

Screenshot 2024-12-03 at 14 50 37

Screenshot 2024-12-03 at 14 50 44

Screenshot 2024-12-03 at 14 50 49

Screenshot 2024-12-03 at 14 50 55

Screenshot 2024-12-03 at 14 51 00

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1208894175510790) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by oetherington** [comment]
CC @agnesstenlund

**Comment by agnesstenlund** [comment]
> Disable scrolling between weeks
does this mean you can't scroll but you can still click on previous weeks?

**Comment by oetherington** [comment]
@agnesstenlund Yep, exactly

**Comment by agnesstenlund** [comment]
Looks great!! 🚢

**Review by Will-Howard — APPROVED** [review]
LGTM apart from those small wording/link things

**Pull request merged**
