### PR TITLE
This is an attempt to fix the RecentDiscussionFeed error

### PR DESCRIPTION
**Pull request by ajroberts0417**
1. "GraphQLError: Field error: value is not an instance of Date", on the RecentDiscussionFeed, which is a MixedTypeFeed, and requires a 'cutoff'. The 'cutoff' value does not seem to be a Date, which is required by the schema?

2. Investigating further:
    - The RecentDiscussionFeed Query should return data and an error (the above error). When using a breakpoint, I found that the data from the `useQuery` call in the MixedFeedType component remains undefined, it has `error` but no data. This doesn't make sense because when executing the same API call against the server directly (using GraphiQL), both data and error are returned.
    - MixedTypeFeed, line 121

### CODE REVIEW

**Comment by ajroberts0417** [comment]
oops, I keep accidentally trying to merge pull requests against the wrong fork, I'll disconnect my fork on github so this stops happening!

**Comment by jimrandomh** [comment]
I believe this is a symptom of having an empty/almost-empty database. It's been awhile since we've tested that use case (as opposed to testing with our pre-seeded development DB). My first guess at what's happening here is it's trying to git the date of the last visible post in the feed, so that if it makes another query it knows where the first page ends and second page starts, but there aren't any posts so there is no "last visible post" to check.

**Comment by jimrandomh** [comment]
Fixed in: https://github.com/ForumMagnum/ForumMagnum/pull/4460

**Comment by ajroberts0417** [comment]
Amazing, thanks!

**Pull request closed without merging**
