### PR TITLE
Allow sorting by inflation adjusted karma on topic pages

### PR DESCRIPTION
**Pull request by Will-Howard**
Apparently this just needed to be enabled. I would like to make this work in subforums too, but that's a bit fiddlier due to the mixed type feed logic. I may add that to this PR but I think it's fine to merge as is, the current behaviour is to fall back to "magic" in the subforum if the sorting is set to topAdjusted in the wiki tab

Screenshot 2022-12-19 at 15 16 52

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203580698488570) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by jpaddison3** [comment]
@darkruby501 want this to be Forum-gated?

**Review by s-cheng — APPROVED** [review]
🦭 

Though since you're here, it would be great to improve the ordering of the options. On the wiki tab posts list, I think "Top" should go above "Top (Inflation Adjusted)".
Screen Shot 2022-12-20 at 3 56 08 PM

Then on the subforum feed, the order is different and should probably just be the same order as on the wiki tab?
Screen Shot 2022-12-20 at 3 57 19 PM

**Comment by Will-Howard** [comment]
> @darkruby501 want this to be Forum-gated?

I'm going to assume not and merge this, seeing as LW already has the inflation adjusted sorting on the all posts page, but I'm happy to change this after the fact

**Comment by darkruby501** [comment]
Sorry, didn't see this, yeah, seems fine!

**Pull request merged**
