### PR TITLE
Post page donation button [WIP]

### PR DESCRIPTION
**Pull request by Raemon**
This is the version of the donation button for the PostsPage. By default this will be displayed for ~a week for top-ranked posts in the review. If they get a fair amount of traction, we may leave them up longer, but it'll depend on some bigger discussions about what's good for LW.

The current version's paypal link doesn't work properly – it worked when I tested it for my own personal paypal donation button, but when I switched to the CFAR donation form it no longer auto-filled the donation amount with the one entered on LessWrong, and I couldn't get rid of the "recurring payment?" checkbox.

Most of what's available to review so far is the style.

Exerimented with a few tooltips but wasn't satisfied with them. I'm considering making "Best of LessWrong 2020" to be a link the the voting-results post, with a post-style hoverpreview.

image
image

### CODE REVIEW

**Comment by darkruby501** [comment]
I don't like the styling of "Best of LessWrong 2020", it needs something more.
Maybe:
- Make it green and a link to the Best of 2020 winners post
- Make it larger and make it Serif font
- Give it a background (looking like the tag stylings)

Really, I'd want its size to be larger than the donate button.

Actually thinking about it, the framing I might much prefer is "Tip this author"

**Comment by Raemon** [comment]
Updated UI a bit.

(note: I think fine-tuning the exact UI here is a bit of a nice-to-have relative to getting the functionality working)

image
image

**Comment by Raemon** [comment]
I don't know that I like the "tip author" frame because it brings to mine "dropping a few cents into a jar", when what I want is "think about whether this post significantly improved your life, or humanity's trajectory, and pay the author something commensurate with that."

**Comment by Raemon** [comment]
Closing since it

**Pull request closed without merging**
