### PR TITLE
Filter out admin-only Topic updates from recent discussion

### PR DESCRIPTION
**Pull request by jpaddison3**
Lizka is about to drop a huge update on the wiki main page. I want it not to blow up recent discussion, which it totally would. I think this is a change that should happen anyway.

@darkruby501 please let me know monday if you don't want this on LW.

### CODE REVIEW

**Comment by jpaddison3** [comment]
Note: you might think we should filter this out when querying the DB, but the DB query is on the revisions table, which doesn't have access to this data.

**Comment by darkruby501** [comment]
I looked at this but don't understand the use case. What does this do and why do you want it?

**Comment by jpaddison3** [comment]
This change hides updates to the wiki for admin-only topics from appearing on the home page. These changes are noisy and not relevant for non-admin users, so I want to hide them.

Maybe I didn't answer your question? If so let me know.

**Comment by darkruby501** [comment]
Oh, I didn't realize that we had tags that only admin-editable. I thought we had "only admin-viewable" 

Makes sense. Yet, filtering out edits to Concepts Portal Page and Tag CTA Text makes perfect sense. Please proceed.

**Pull request merged**
