### PR TITLE
Author analytics improvements 2024 05

### PR DESCRIPTION
**Pull request by oetherington**
UI updates for the author analytics and post analytics pages. [Relevant Figma](https://www.figma.com/design/qAHRGADVOGojqKpqbGMFFu/2024-Q2?node-id=272-18189&m=dev).

## Author stats page

Screenshot 2024-05-21 at 19 48 09

Screenshot 2024-05-21 at 19 52 28

## Post stats page

Screenshot 2024-05-21 at 19 53 23

Screenshot 2024-05-21 at 19 53 14

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1207372141657441) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by agnesstenlund** [comment]
thanks so much @oetherington!! This is very close to perfect 👏 

Small improvements:

- [ ] This is my fault cause my mockup was incorrect, but I think we shouldn't show the pointy finger cursor when hovering "Views" and "Reads" since it makes them look clickable
Screenshot 2024-05-22 at 17 44 24

- [ ] The headers + graph should all be left-aligned
Screenshot 2024-05-22 at 17 33 56

- [ ] Not new, but the shadow on the hover in light mode looks really dark + aggressive
Screenshot 2024-05-22 at 17 33 02

- [ ] On the individual stats page, we should remove the "Daily stats" hover since that feels self-explanatory and makes it look weird with two headings. And all of these should be left-aligned too :)
Screenshot 2024-05-22 at 17 35 40

- [ ] On mobile, the filters are in two columns on the individual page but not on the overview. Looks nicer with two columns
Screenshot 2024-05-22 at 17 37 26
Screenshot 2024-05-22 at 17 37 14

- [ ] Would be great to have consistent margin on the overview + individual page. Looks like the overview page have more margin (most visible on mobile). Ideally the pages would have no margin on desktop and some margin on mobile
Screenshot 2024-05-22 at 17 37 40
Screenshot 2024-05-22 at 17 37 14

**Comment by jpaddison3** [comment]
It's very slow to reorder my posts based on views, when I connect to the prod db.

**Comment by jpaddison3** [comment]
I loaded this in fast 3G and saw a loading spinner instead of a skeleton.

**Comment by jpaddison3** [comment]
(I am an idiot) (Ok, trying again)

This is an @agnesstenlund question really, but I would have thought that my hover of the number would show the read tooltip, not just the word read.

**Review by jpaddison3 — APPROVED** [review]
ASTLAC, excellent stuff.

**Comment by agnesstenlund** [comment]
> I would have thought that my hover of the number would show the read tooltip, not just the word read.

- [ ]  Ah I agree, even better if hovering the the text below +  also the big number will trigger the tooltip

**Comment by oetherington** [comment]
@agnesstenlund Thanks - I think all points should be fixed now!

**Comment by agnesstenlund** [comment]
Lovely! My localhost refuses to load but if code looks good we can merge 👍

**Comment by oetherington** [comment]
Great - I'll merge now and we can tweak later if we want any more changes

**Pull request merged**
