### PR TITLE
Simplify post card view in subforum page

### PR DESCRIPTION
**Pull request by Will-Howard**
- Only show 3 comments
 - Start all comments collapsed

Screenshot 2023-01-23 at 13 26 07
Screenshot 2023-01-23 at 13 29 34

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203801843516939) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by Xodarap** [comment]
I don't know why, but I'm still seeing comments not collapsed by default

image

**Comment by Will-Howard** [comment]
> I don't know why, but I'm still seeing comments not collapsed by default
> 
> image

Hmm I can't replicate this. Is this in the subforum page? This change doesn't affect the normal recent discussion feed

**Comment by Xodarap** [comment]
Oh, I think what's going on here is that comments on posts are collapsed, but not comments on discussions. But we are getting rid of discussions anyway so 🤷

**Review by Xodarap — APPROVED** [review]
:shipit:

**Pull request merged**
