### PR TITLE
EA Forum typography tweaks

### PR DESCRIPTION
**Pull request by oetherington**
FYI @agnesstenlund 

- Capitalize titles on the sequence page (instead of all uppercase)
Screenshot 2023-07-03 at 13 18 21

- Fix serif on quick takes content warning
Screenshot 2023-07-03 at 13 20 29

- Fix serif on vote count for unreviewed posts in sunshine sidebar
Screenshot 2023-07-03 at 13 38 47

- Fix serif on "Link" button when adding posts to a sequence
Screenshot 2023-07-03 at 13 42 28

- Fix serif for notification settings
Screenshot 2023-07-03 at 13 44 08

- Fix serif for notifications "Load more" button
Screenshot 2023-07-03 at 13 47 14

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204955177920355) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by Will-Howard — APPROVED** [review]
LGTM as far as the code is concerned, up to you whether you want to wait for @agnesstenlund 's approval before merging

**Comment by agnesstenlund** [comment]
Perfect 🥲

**Comment by agnesstenlund** [comment]
Oh actually, one small one: think I would prefer Sentence case over Capitalized Case for the sequence titles

**Comment by oetherington** [comment]
You mean just leave it as the user types it, right? That probably makes the most sense to me.

**Comment by jpaddison3** [comment]
Ya

**Comment by oetherington** [comment]
For now, I've implemented it as JP said above but we can tweak in the future if necessary.

The problem with sentence case is that it would transform, for instance, "AI" into "Ai" which is a bit weird.

**Comment by agnesstenlund** [comment]
makes 100% sense 👍

**Pull request merged**
