### PR TITLE
Fix a crash and XSS in FootnotePreview

### PR DESCRIPTION
**Pull request by jimrandomh**
Link anchors with special characters could crash footnote preview, breaking some links in posts such as http://localhost:3000/posts/ttjebJSR7HsLDbqky . Also there was an XSS in the transform that removed the footnote backlink.

### CODE REVIEW

**Comment by Discordius** [comment]
Lint error looks real

**Comment by jimrandomh** [comment]
Lint is not real (it's swallowing the exception on purpose); added an `eslint-ignore-next-line`.

**Comment by Discordius** [comment]
Sorry, I meant real in the sense that we either need to adjust our lint rules, or add an eslint-ignore.

**Review by Discordius — APPROVED** [review]

**Review by jpaddison3 — APPROVED** [review]

**Comment by jpaddison3** [comment]
I'm merging this because LW saw the bug live and I don't like leaving live bugs on the site.

**Pull request merged**
