### PR TITLE
[EA Forum only] allow users to display their bio at the bottom of their posts

### PR DESCRIPTION
**Pull request by s-cheng**
We're experimenting with ways to encourage more users to message others based on things they write on the forum. The first thing we're testing out is adding an option for users to display this post author card with a snippet of their bio at the end of their posts.

Screen Shot 2022-06-22 at 10 11 32 PM

-----
On smaller screens, the buttons move under the username:

Screen Shot 2022-06-22 at 10 12 03 PM

-----
If the author has a photo, we'll also show that:

Screen Shot 2022-06-23 at 12 54 39 AM

### CODE REVIEW

**Comment by jpaddison3** [comment]
I would strongly consider hiding this if the post is going to display the sequence navigation at the bottom.

**Comment by s-cheng** [comment]
@jpaddison3 I actually specifically tested with a post that had all the things at the bottom - tags, vote, sequence nav, pingbacks. Personally I thought it was fine? And the reader can skip to the comments if they want, via the ToC. But let me know if you disagree - I already hide it for events, so it's prob nbd if you want me to hide it when in a sequence.

**Comment by jpaddison3** [comment]
I lean towards thinking we should hide it, but I'd understand if you wanted to ship this and do that later.

**Review by jpaddison3 — APPROVED** [review]
ASTLAC

**Pull request merged**
