### PR TITLE
Visited link color

### PR DESCRIPTION
**Pull request by Raemon**
Gears of Ascension argues we really should have visited-link colors, to help people keep track of their reading and make link-dense exploration less overwhelming. I'm inclined to agree. 

Figuring out an actually good color is kinda annoying. It can't be a variant of green (or whatever the forum main color is), because then if you're on a post where you've read all the links, it's unclear if you're looking at a link you haven't read or not. It can't be grey because it's just too hard to read. 

I actually kinda like this slightly yellowish-brownish-grey, which stands out but feels like it matches the green in an earth-tone vibe. I also don't think it looks too crazy on EA Forum. AI Alignment Forum feels most questionable. (although you could certainly pick new colors for those if you want). My model of Oli is super opinionated about it on LW though.

https://app.intercom.com/a/inbox/wtb8z7sj/inbox/shared/all/conversation/27439410251?view=List

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1203890338238303) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by Raemon** [comment]
@jpaddison3 I assume someone on your design team should look at this, maybe it's you, not sure who.

**Comment by agnesstenlund** [comment]
Thanks @oetherington! Happy that we're doing this. Visited links are typically purple, any reason you didn't want to go with that? ([See this, for example](https://accessibility.huit.harvard.edu/technique-visited-links))

It also looks like there isn't enough contrast to make that color accessible in light mode:
Screenshot 2023-02-06 at 16 05 47

**Comment by jpaddison3** [comment]
I'd suggest resolving in slack? Happy that you like the principle of the thing Agnes, I do too.

**Comment by Raemon** [comment]
visited links aren't purple because it clashes with the rest of our color scheme. (Normally when visited links are purple, regular links are blue, and in this case the regular links aren't blue and the whole surrounding color schemes aren't designed to match)

I will look into getting it more constrasty tho

**Comment by agnesstenlund** [comment]
Yup I realised that too, since your links are green this colour does make more sense for you. For the EA forum with blue links, a purple would be better

**Comment by Raemon** [comment]
Okay, I shipped a tweak which should make it purple on EA Forum and darkens the brown-color a bit (FYI neither EA Forum nor LW's current main link color actually registers as high-constrast enough. When I try making it darker it looks pretty jarring to me and I think we may have chosen the lighter color on our end purpose. For now I was shooting for "the visited-color is at least comparable contrast to the normal color)

**Comment by Raemon** [comment]
EA Forum:

image

**Comment by Raemon** [comment]
somewhat darker LW color

image

**Comment by jpaddison3** [comment]
image

**Review by jpaddison3 — APPROVED** [review]

**Pull request merged**
