### PR TITLE
[EA Forum only] move bookmark icon out of post item, replace with three dots menu

### PR DESCRIPTION
**Pull request by s-cheng**
This PR moves the bookmark icon out of the EA Forum's post item into the three dots menu, and moves the three dots menu icon into the post item.

Screen Shot 2023-04-26 at 12 12 24 PM

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1204480829488979) by [Unito](https://www.unito.io)

### CODE REVIEW

**Review by oetherington — APPROVED** [review]
Thanks!

I also just added one more small commit to change the hover styles for the triple dot icon so that they match the hover styles for the comments icon - it was annoying me that one of them got darker on hover and one of them got lighter.

**Comment by agnesstenlund** [comment]
Sorry I forgot to hit "Comment" after I wrote my comment 🤦‍♀️  had some small notes (thanks for the comment on the hover style @oetherington! that was one of them)

- The icon looks a little fat/ big. Not sure if it's the size or the icon itself, changing the size makes it look almost too small? This is what it looks like when I change from 24px to 20px:
Screenshot 2023-04-27 at 16 36 47


- Looks like we're using another color than the other icons, I'd actually use the upvote karma color here which is lighter (#bdbdbd)
Screenshot 2023-04-27 at 16 33 57

**Comment by agnesstenlund** [comment]
Ohh also just remembered we use the same icon here, but vertical instead of horizontal
Screenshot 2023-04-27 at 16 46 40

not sure yet if this updates me in favour of vertical ellipsis everywhere, or horizontal everywhere. Maybe the first. @s-cheng any takes?

**Comment by s-cheng** [comment]
@agnesstenlund Hmm yeah I'm not sure, but I think the vertical looks slightly better here so maybe I'd go with that:

Screen Shot 2023-04-27 at 2 52 17 PM
Screen Shot 2023-04-27 at 2 51 35 PM

**Pull request merged**
