### PR TITLE
Giving portal updates 2023-12-22

### PR DESCRIPTION
**Pull request by oetherington**
Giving portal updates requested by Toby, preparing for the end of giving season.

- Various copy updates
- Add "Donate now" section to top of page
- Add description tooltips to election candidates
- Limit list of "other features candidates" to a specific set of 13 charities

Screenshot 2023-12-22 at 13 02 09
Screenshot 2023-12-22 at 13 02 27
Screenshot 2023-12-22 at 13 02 34
Screenshot 2023-12-22 at 13 02 46

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201302964208280/1206230023489516) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by oetherington** [comment]
Updates:

- Copy additions and remove CTA buttons

Screenshot 2023-12-22 at 17 00 50

- Move EA funds options onto a single line (larger screens only)

Screenshot 2023-12-22 at 17 00 42

**Comment by oetherington** [comment]
- Added a second hero image
Screenshot 2023-12-22 at 17 07 38

**Review by s-cheng — APPROVED** [review]
I can't access the doc with the requirements, but I assume this looks correct 👍 

I think it's pretty likely that we will want to run a version of Giving Season in 2024, so we should think about how we want to clean up all the relevant code. (Or at least add some comments to help our 2024 selves.) I think leaving a bunch of commented out stuff will be confusing.

**Comment by oetherington** [comment]
@s-cheng Great, thanks!

Yeah - it's a bit of a mess a the moment. I just commented stuff out for now as I wasn't sure if some of it might end up getting reenabled, but I think some post-giving-season clean-up would definitely be justified.

**Pull request merged**
